#!/bin/bash
cd /mnt/c/Users/ffg/Downloads/WEM/web_ready

mv "imagen031.webp" "bolsa-hdpe-negra.webp"
mv "imagen032.webp" "bolsa-negra-industrial.webp"
mv "imagen033.webp" "rollo-estirable-negro.webp"
mv "imagen034.webp" "rollo-estirable-transparente.webp"
mv "imagen035.webp" "rollo-film-negro.webp"
mv "imagen036.webp" "film-industrial-hdpe.webp"
mv "imagen037.webp" "bolsa-blanca-asa.webp"
mv "imagen038.webp" "bolsa-hdpe-blanca.webp"
mv "imagen039.webp" "bolsa-industrial-transparente.webp"
mv "imagen040.webp" "bolsa-reutilizable-blanca.webp"
mv "imagen041.webp" "bolsa-transparente.webp"
mv "imagen042.webp" "bolsa-tipo-super-ecologica.webp"
mv "imagen043.webp" "bolsa-ecologica-transparente.webp"
mv "imagen044.webp" "banner-promocional-verde.webp"
mv "imagen045.webp" "banner-promocional-amarillo.webp"
mv "imagen046.webp" "banner-wem-oficial.webp"
mv "imagen047.webp" "banner-oficial-verde.webp"
mv "imagen048.webp" "grafico-promocional-eco.webp"
mv "imagen049.webp" "grafico-promocional-cuidado.webp"
mv "imagen050.webp" "imagen-comercial-bolsa.webp"
mv "imagen051.webp" "imagen-bolsa-hdpe.webp"
mv "imagen052.webp" "bolsa-transparente-limpieza.webp"
mv "imagen053.webp" "bolsa-con-cierre-hdpe.webp"
mv "imagen054.webp" "imagen-hogar-bolsa.webp"
mv "imagen055.webp" "rollo-industrial-blanco.webp"
mv "imagen056.webp" "film-industrial-transparente.webp"
mv "imagen057.webp" "rollo-polietileno-blanco.webp"
mv "imagen058.webp" "film-paletizado-productos.webp"
mv "imagen059.webp" "banner-productos-wem.webp"
mv "imagen060.webp" "banner-promocional-plastico.webp"
