#!/bin/bash
cd /mnt/c/Users/ffg/Downloads/WEM/web_ready

mv "imagen001.webp" "bolsa-basura-negra-industrial.webp"
mv "imagen002.webp" "bolsa-basura-negra.webp"
mv "imagen003.webp" "bolsa-de-plastico-hdpe-blanca.webp"
mv "imagen004.webp" "bolsa-transparente-hdpe.webp"
mv "imagen005.webp" "bolsa-supermercado-asa.webp"
mv "imagen006.webp" "bolsa-biodegradable-verde.webp"
mv "imagen007.webp" "bolsa-tipo-super-blanca.webp"
mv "imagen008.webp" "bolsa-tipo-super-transparente.webp"
mv "imagen009.webp" "rollo-film-estirable-industrial.webp"
mv "imagen010.webp" "rollo-film-estirable-negro.webp"
mv "imagen011.webp" "rollo-polietileno-negro-industrial.webp"
mv "imagen012.webp" "rollo-polietileno-alta-densidad.webp"
mv "imagen013.webp" "rollo-negro-industrial-polietileno.webp"
mv "imagen014.webp" "rollo-plastico-negro-industrial.webp"
mv "imagen015.webp" "rollo-plastico-transparente.webp"
mv "imagen016.webp" "banner-promocional-wem.webp"
mv "imagen017.webp" "banner-oficial-wem-amarillo.webp"
mv "imagen018.webp" "banner-oficial-wem.webp"
mv "imagen019.webp" "grafico-promocional-ecologico.webp"
mv "imagen020.webp" "grafico-promocional-hogar.webp"
mv "imagen021.webp" "grafico-ecologico-limpieza.webp"
mv "imagen022.webp" "imagen-comercial-bolsa-hdpe.webp"
mv "imagen023.webp" "bolsa-de-plastico-frutas.webp"
mv "imagen024.webp" "bolsas-sustentables-blancas.webp"
mv "imagen025.webp" "bolsa-hdpe-promocional.webp"
mv "imagen026.webp" "bolsa-ecologica-biodegradable.webp"
mv "imagen027.webp" "bolsas-biodegradables-verdes.webp"
mv "imagen028.webp" "bolsa-transparente-sin-asas.webp"
mv "imagen029.webp" "bolsa-transparente-cierre.webp"
mv "imagen030.webp" "bolsas-plasticas-reutilizables.webp"
